#!/usr/bin/env bash
# A rebuild script that commits on a successful build
# https://gist.github.com/0atman/1a5133b842f929ba4c1e195ee67599d5
set -e

# cd to your config dir
pushd /etc/nixos

# Edit your config
# $EDITOR configuration.nix

# Autoformat your nix files
alejandra .

# Shows your changes
# it's not recursive :(
# git diff -U0 *.nix

echo "NixOS Rebuilding..."

# Rebuild
sudo nixos-rebuild switch --flake /etc/nixos#ahinix 


# Get current generation metadata
current=$(nixos-rebuild list-generations | grep current)

# Commit all changes witih the generation metadata
git commit -am "$current"

# Back to where you were
popd

# Notify all OK!
notify-send -e "NixOS Rebuilt OK!" --icon=software-update-available
