# Source env variables from home-manager
source ~/.nix-profile/etc/profile.d/hm-session-vars.sh

# Configure zoxide
eval "$(zoxide init bash)"

# Configure PATH
PATH=$PATH:~/.bin

# Enable unfree packganes in nix
export NIXPKGS_ALLOW_UNFREE=1

# make fish default shell
if [[ $(ps --no-header --pid=$PPID --format=comm) != "fish" && -z ${BASH_EXECUTION_STRING} ]]
then
	shopt -q login_shell && LOGIN_OPTION='--login' || LOGIN_OPTION=''
	exec fish $LOGIN_OPTION
fi
